create table if not exists public.orders (
  id text primary key,
  created_at timestamptz not null default now(),
  status text not null default 'new' check (status in ('new', 'accepted', 'preparing', 'completed', 'canceled')),
  guest_name text not null,
  phone text not null,
  address text,
  fulfillment text not null check (fulfillment in ('Delivery', 'Pickup')),
  note text,
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  service_fee numeric(10, 2) not null default 0 check (service_fee >= 0),
  delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0),
  total numeric(10, 2) not null check (total >= 0)
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  menu_item_id integer not null,
  name text not null,
  category text not null,
  price numeric(10, 2) not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(10, 2) not null check (line_total >= 0)
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists public_orders_insert on public.orders;
create policy public_orders_insert
  on public.orders
  for insert
  with check (true);

drop policy if exists public_orders_read on public.orders;
create policy public_orders_read
  on public.orders
  for select
  using (true);

drop policy if exists public_orders_update_status on public.orders;
create policy public_orders_update_status
  on public.orders
  for update
  using (true)
  with check (status in ('new', 'accepted', 'preparing', 'completed', 'canceled'));

drop policy if exists public_order_items_insert on public.order_items;
create policy public_order_items_insert
  on public.order_items
  for insert
  with check (true);

drop policy if exists public_order_items_read on public.order_items;
create policy public_order_items_read
  on public.order_items
  for select
  using (true);
